### ISSUE TITLE
Use deepseq to allow for forcing data

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#104]
We could implement a "deeply strict" identity function like so:
```haskell
forceS = MSF $ \a -> a `deepseq` return (a, forceS)
```
It completely forces the data passing through it before continuing. (Note this isn't `arr force`, which doesn't work.)
This isn't urgent, but it's useful when using wormholes to put expensive computations into separate threads.

The downside is that it introduces deepseq as a dependency, but that's not such a huge problem, I find.

**Comment by ivanperez-keera** [comment]
Because you have asked to get more prompt replies, I'll reply.

I'm summarily delaying all performance-related issues until we have the right framework to do this right. As I said in a different comment, we have an intern coming to study how to do this generally for FRP frameworks, and dunai and Yampa should benefit from that.

That may give us a more systematic way of approaching all performance limitations and improvements.
