### ISSUE TITLE
Analyse efficiency of strictness annotations

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#20]
We need to find out which `seq`s and bangs actually improve efficiency, and add them systematically.

**Comment by ivanperez-keera** [comment]
I would totally delay this if we can. If we can not add them at all, then great. I consider working on the efficiency of this library something with tiny priority at this point.

99.9% of the times, optimisations make code harder to understand. They also make deducing things about the code ("what is core, what isn't") and maintaining that code much harder (the amount of code is essentially multiplied by 4 in Yampa due to GATDs).

There are two key, extremely important ideas that dunai can answer: one of them is what is minimal in FRP and the other is how can other FRP flavours be implemented using dunai.

Working on efficiency, unless we got to the point of the discussion when we need to compare the efficiency of two implementations, will make code harder to understand.

For now, work on efficiency and strictness should be limited only to finding out whether something is inherently inefficient or leaky, when we suspect it is.

**Comment by ivanperez-keera** [comment]
(and so I suggest we close this issue for now.)

**Comment by turion** [comment]
I agree on the minimality point. But shouldn't we try and _remove_ the `seq`s in order to unclutter the code?

**Comment by ivanperez-keera** [comment]
I have limited hands and limited time. Ideally, we could. But clearing those away also rates very low at this point. If performance overhead, unless intrinsic to our abstraction, is not a priority, then we should completely ignore all those aspects of it for now. This includes inlining (doing this right is not a small feat, it requires a lot of work).

**Comment by turion** [comment]
I agree on everything you say. I just don't want to completely forget about the issue.

**Comment by ivanperez-keera** [comment]
We won't forget about the major idea (performance tuning), or about these specifics.

Inlining and seqs are basic performance tuning techniques in Haskell. There is zero chance that we will start evaluating efficiency and not consider either of them.

And given the fact that we use this library for games, you use this for audio, and performance has historically been an important issue in FRP, it's something that will regularly pop into our minds and sooner or later we will need to address property (just not yet). Also, when we write papers, we will necessarily need to talk about it. So it'll come back again and again.

That's why I'm not worried about forgetting this: the normal workflow and the field makes me remember this all too often.

I'm keeping notes and ideas about performance tuning in a separate place (a folder at home, and a separate repo where I experiment about things when I'm curious, until I have the time to work on it properly, both for Yampa and for dunai).
