### ISSUE TITLE
Simplify Travis setup with cabal projects

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#205]
In rhine, I recently vastly reduced the number of Travis CI jobs - thus speeding up the pipeline - by building all packages in one job using cabal projects. Here is an example: https://github.com/turion/rhine/blob/9dbcf9cba810b88a4685f473ceaf0af77c1c5bc3/.travis.yml

This may or may not be applicable in Dunai as well. Some packages failed in specific GHC versions, and I don't know whether they still do.

**Comment by ivanperez-keera** [comment]
I agree with the sentiment and desire to simplify this.

Part of this would probably require determining what examples should be included and tested and what shouldn't.

**Comment by turion** [comment]
Ah, there is already a PR in that direction: https://github.com/ivanperez-keera/dunai/pull/166

**Comment by turion** [comment]
Then this issue is about adapting `.travis.yml` to the cabal project.

**Comment by turion** [comment]
> Part of this would probably require determining what examples should be included and tested and what shouldn't.

Why should certain examples not be included and tested? Because they don't work well on CI?

**Comment by ivanperez-keera** [comment]
They take quite a long time, and, especially those with UI functions, can easily break due to reasons unrelated to dunai.

If we would release a dunai when one of those examples is still broken, then that particular example probably does not belong in the battery of tests.

Having a very long CI build leaves me mentally exhausted (for good reason) and unable to truly work on dunai as much as I'd love to. Maintenance needs to be "cheap" and easy. That means PRs (even my own) need to be simple to check and merge, or this will become the perfect battery of tests that nobody will ever use.

**Comment by turion** [comment]
> If we would release a dunai when one of those examples is still broken, then that particular example probably does not belong in the battery of tests.

Such tests should then be part of a separate repository maybe, and have their own CI (which doesn't need to run as quickly since there aren't as many changes).

> Having a very long CI build leaves me mentally exhausted

Yep. Same here. I start some PRs and push them, then I stop working because CI takes at least until tomorrow. That's why I want to cut down CI time.

**Comment by ivanperez-keera** [comment]
I agree that some of these tests are not essential, so I'm going to cut them down and try to build everything in one go.
