### ISSUE TITLE
Can we write concatS without access to unMSF?

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#221]
The module `Data.MonadicStreamFunction.Async` is an odd one: it needs access to the MSF constructor, where many other constructs do not.

I think the best way for this in the current library is probably with Util or one of the modules under `Control`, but I only want to move it really belongs there, either because it can be best expressed in the same terms as the module (if under `Control`), or if it can be expressed without access to `unMSF` (if under `Util`).

I wonder if 1) there is a way to write this without access to the data constructor `MSF` and `unMSF` and, if so 2) what are the different, equivalent ways of writing this, and which one is the most appropriate (meaning, for example, the one expressed in terms that best describe what is happening at the level of abstraction used in the context).

**Comment by turion** [comment]
I thought about that a lot, but it's long ago. I think I tried a lot to implement it with exception handling, but I couldn't get it to work. Asynchronous operations fundamentally need access to `unMSF` because they need to control when the inner `MSF` runs.

The particular function `concatS` might be better moved to `Control.Monad.Trans.MSF.List`, since it contains other functions which also control how `MSF`s interact with lists.
