### ISSUE TITLE
(question): using `embed` with a `constant 1.0` MSF to get (printable) results

### ISSUE THREAD

**Issue by madjestic** [ivanperez-keera/dunai#246]
Hey guys,

I am trying to use `embed` function with a `constant` function and I expect to get a (printable) result back:
```haskell
embed (constant 1.0) [()]
```
it type-checks, but I get an error:
```bash
"    • No instance for (Show (ClockInfo m0 [Double]))
        arising from a use of ‘print’
```
In Yampa you'd do something like that:
```haskell
embed (constant 1.0) ((), [(1.0), Nothing])
> [(1.0)]
```

I wonder how it's done properly in dunai/bearriver?
The bearriver docs mention "To explore the output progressively, use arrM and '(>>>)'', together with some action that consumes/actuates on the output.", but I don't find that very helpful.  Could I get a conrete example, please?

Here's a (toy) function that I began with:
```haskell
fallingBall :: (Monad m) => Pos -> MSF (ClockInfo m) () (Pos, Vel)
fallingBall pos = constant pos &&& constant 0.0
```

Now, I would like to use `embed` to print out some results.  How can I do that, using `embed`?

Thanks,
Vlad

**Comment by turion** [comment]
I'm not completely sure, but I think the issue is that your monad isn't specified. Imagine `m` was `IO`, then you'd try to show a `ClockInfo IO [Double]`, which you can't, before you've _run_ the `IO` effect. The same is true for `ClockInfo`. See https://hackage.haskell.org/package/bearriver-0.13.1.2/docs/FRP-BearRiver.html#t:ClockInfo: It's a `ReaderT` effect that specifies the length of a time step. You have to specify the simulation time step, either before or after `embed`.

Here is an untested suggestion you could try:

```haskell
runIdentity $ flip runReaderT 0.1 $ embed (constant 1.0) [()]
```

The `runReaderT` part sets the simulation time step to 0.1. The `runIdentity` unifies the monad to `Identity` and retrieves the result.

If you want `IO`, you could do this:
```haskell
main = do
  result <- flip runReaderT 0.1 $ embed (constant 1.0) [()]
  print result
```

If you want to set the simulation time steps dynamically from another `MSF`, you can use https://hackage.haskell.org/package/dunai-0.7.0/docs/Control-Monad-Trans-MSF-Reader.html#v:runReaderS. (Or even use clocks, like in https://github.com/turion/rhine)

**Comment by madjestic** [comment]
Wow, that's s great answer, @turion , thank you!  I will try running the code asap.

**Comment by madjestic** [comment]
Works like a charm!

```haskell
runIdentity $ flip runReaderT 0.1 $ embed (constant 1.0) [(),(),()]
[1.0,1.0,1.0]
```

Thanks,
Vlad
