### ISSUE TITLE
Reorg: Function naming

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#26]
The nomenclature used for the API is not intuitive. Why are is there a function called `arrM`, another called `arr` and another `liftS`, when they all have similar signatures?

This needs to be improved.

The naming convention needs to be such that the entry barrier to entry is minimal. I'd rather use names related to signal processing than operational notions (step), but the latter may be unavoidable.

**Comment by turion** [comment]
I'm proposing the following naming guidelines:

* Suffix `M` generalises something to monads. Example: `arrM :: (a -> m b) -> MSF m a b`
* Suffix `S` generalises something to streams or stream functions. Example: `concatS :: MStream m [b] -> MStream m b`
* Suffix `_` specialises to something not having an input. Example: `arrM_ :: m b -> MSF m a b`
* `lift` means lifting into a monad transformer
* `liftBase` means lifting into a monad base
* `hoist` means applying a (general) monad morphism
* `run` means removing a monad transformer layer

This way, all the names follow a clear and standard pattern.
It would imply the following (and maybe other) renames:

* `liftS` -> `arrBase :: (Monad m2, MonadBase m1 m2) => (a -> m1 b) -> MSF m2 a b`
* `liftMSFPurer` -> `hoistS :: (Monad m2, Monad m1) => (forall c . m1 c -> m2 c) -> MSF m1 a b -> MSF m2 a b`
* `liftMSFTrans` -> `liftS :: (MonadTrans t, Monad m, Monad (t m)) => MSF m a b -> MSF (t m) a b`
* `liftMSFBase` -> `liftBaseS :: (Monad m2, MonadBase m1 m2) => MSF m1 a b -> MSF m2 a b`

This would break some code in articles and @ivanperez-keera 's thesis, though.

If you're fine with this, I'll submit a pull request.

**Comment by ivanperez-keera** [comment]
A few comments:

* It's ok if my thesis breaks. Ideally it shouldn't at the time of submission, but eventually it will. We can't hold back progress because I wrote a thing.

   I'd rather just update the examples in the final submission if the reviewers agree, or add a file to some repo with the examples in the thesis for the updated API.

* My intuition is that if something ends in `_`, the type is `h ()` for some `h` (probably an `MSF m a ()`). For instance, I'd call `arrM_` `constM`.

* I didn't know the word hoist, but the meaning seems similar to lift. But the meaning in our library is transforming *horizontally*, not always vertically. Why not something that sounds like transform, or morph, or change, or convert?

Let's think a bit harder about those. Maybe ask for other people's opinion too?

**Comment by turion** [comment]
> It's ok if my thesis breaks. I'd rather just update the examples in the final submission if the reviewers agree, or add a file to some repo with the examples in the thesis for the updated API.

Ok.

> My intuition is that if something ends in `_`, the type is `h ()` for some `h` (probably an `MSF m a ()`).
Ah yes, you're right.

> For instance, I'd call `arrM_` `constM`.
Or rather `constArrM` or `arrMConst`?
> I didn't know the word hoist, but the meaning seems similar to lift. But the meaning in our library is transforming horizontally, not always vertically. Why not something that sounds like transform, or morph, or change, or convert?
I've seen it used e.g. in [pipes](http://hackage.haskell.org/package/pipes-3.1.0/docs/Control-MFunctor.html#v:hoist) or in [mmorph](http://hackage.haskell.org/package/mmorph-1.0.0/docs/Control-Monad-Morph.html#v:hoist). There, it means applying a monad morphism within a transformer stack. So since `MSF` is something like a transformer, I wanted to draw the parallel.

> Let's think a bit harder about those. Maybe ask for other people's opinion too?
Sure :) as long as a version is released on hackage before HAL 2017, that's fine.
How about asking people in the FP lab?

**Comment by ivanperez-keera** [comment]
> How about asking people in the FP lab?
Go for it. Wherever you think it's best.

**Comment by turion** [comment]
> Go for it. Wherever you think it's best.

Well, I'm not there ;) but maybe you are?

**Comment by ivanperez-keera** [comment]
Nope. fp-lunch?

**Comment by turion** [comment]
I just realised that you've already released version 0.1.1.0 and [rhine](https://github.com/turion/rhine) compiles with it! In that case, I'm fine with leaving this issue to rest until HAL and asking people there for their opinions.

**Comment by turion** [comment]
### `const`
> My intuition is that if something ends in `_`, the type is `h ()` for some `h` (probably an `MSF m a ()`). For instance, I'd call `arrM_` `constM` or `constantM`.

I like `constM`, and yes, you're absolutely right about `_`.

### `hoist`
> I didn't know the word hoist, but the meaning seems similar to lift. But the meaning in our library is transforming horizontally, not always vertically. Why not something that sounds like transform, or morph, or change, or convert?

I don't know what you mean by horizontally. `lift` goes from an untransformed monad to a transformed monad. The nomenclature from the package `mmorph`, which I'd like to adopt, would suggest to:

* call a monad morphism `morph :: forall a . m a -> n a`
* call the application of a monad morphism to a transformer `hoist :: (forall a. m a -> n a) -> t m b -> t n b`.

Since our `MSF`s are at least `Applicative` transformers, I think it's ok to have the name `hoistS :: (forall c . m1 c -> m2 c) -> MSF m1 a b -> MSF m2 a b`.

### Running and wrapping

One last thing. We already agree on this, but I just want to fix it. There are certain functions in `Control.Monad.Trans.MSF.*` that follow these guidelines:

* `runReaderS` etc. remove the outermost `ReaderT` from the stack, making it explicit in the input. It's analogous to `runReaderT`. This is called a "running function".
* `readerS` etc. adds a `ReaderT` layer to the stack, so it's analogous to the constructor `ReaderT`. This is called a "wrapping function".
* `inMaybeT :: MSF (MaybeT m) (Maybe a) a` etc. insert an effectful value into the monad.

I like this nomenclature, will have a look that it is implemented properly and maybe document it.

### Summary

If you're ok with these decisions I'd go ahead and apply them to the code.

**Comment by ivanperez-keera** [comment]
> > hoist
> > 
> >     I didn't know the word hoist, but the meaning seems similar to lift. But the meaning in our library is transforming horizontally, not always vertically. Why not something that sounds like transform, or morph, or change, or convert?
> 
> I don't know what you mean by horizontally.

Applying `m a -> n a` is a horizontal transformation. In principle, it allows you to move to any monad, even one not in the monad stack. It does not create a monad stack with more monads, or one with less monads.

Applying a function `m a -> t m a` is an example of what I called a vertical transformation: It adds to the monad stack. Removing `(t m a -> m a)` would be another example of a vertical transformation.

The names `lift` and `hoist` make intuitive sense to me for vertical transformations, because English. (It's also what I would expect in Haskell, I guess.) Names like `morph` give no hint towards the direction or characteristics of the transformation (which may be good, sometimes).

**Comment by turion** [comment]
I see, makes sense. I'd say that a general monad morphism `m a -> n a` needn't be necessarily horizontal, then. After all, `lift :: m a -> t m a` is also a monad morphism. So calling general monad morphisms `morph` is a good idea, since it doesn't say anything about the direction.

Yes, the English word `hoist` is quite specifically vertical. Still, I'd rather reuse existing nomenclature, and the package `mmorph` is quite popular, so I'd still suggest following its nomenclature. Look at it like this: `hoist :: (forall a. m a -> n a) -> t m b -> t n b` raises a monad morphism up to a transformer. It's vertical (although its first argumen isn't).

**Comment by ivanperez-keera** [comment]
Given what you said:

> - Suffix S generalises something to streams or stream functions. Example: concatS :: MStream m [b] -> MStream m b

And given that:
```
morph :: forall a . m a -> n a
```
Then I don't understand why the name is not:
```
morphS :: (forall c . m1 c -> m2 c) -> MSF m1 a b -> MSF m2 a b.
```
I'm not trying to argue eternally or anything. I honestly do not see it.

**Comment by turion** [comment]
I think the difference is the following: `morph` is just a monad morphism. `hoist` _takes_ a monad morphism and raises it to a morphism of `MSF`s. The result is a generalisation of `morph` to `MSF`s. So I'd say that `morphS = hoist morph`, for some given monad morphism.

**Comment by turion** [comment]
The suffix `_` was used in `Control.Monad.Trans.MSF.Reader` and other places to distinguish e.g. `runReaderS_ :: Monad m => MSF (ReaderT s m) a b -> s -> MSF m a b` from `runReaderS :: Monad m => MSF (ReaderT s m) a b -> MSF m (s, a) b`, i.e. function argument vs. `MSF` live input. I suggest we keep that convention and apply it to `Control.Monad.Trans.MSF.Random`.

**Comment by ivanperez-keera** [comment]
Which functions would become `hoist*`?

We need to think very carefully about the abstraction and the intuition we want people to work with. I am deeply concerned about making the learning curve as flat as reasonably possible.

The name `hoist` does not convey any intuition about what this is doing without a much deeper understanding of transformers or mmorph, so I'd rather not add it. I prefer a slightly longer name like `morphS` that conveys the intuition by being based on two pre-existing concepts defined in the same module.

Adding specific names for things is common in algebra and category theory (e.g., grupoid, group, ring, semi-ring, category, algebra, and the list goes on and on). It makes discussions more precise, but it also makes learning hard.

`mmorph` is not necessarily something that people will be familiar with. I wouldn't want to make it conceptually a requirement for people to use dunai.

The parallel with other libraries can be drawn elsewhere for now (haddock, tutorials, readme, examples). Maybe in the future `hoist` will be included, but I'm inclined to say 'not for now'.

**Comment by ivanperez-keera** [comment]
> Which functions would become hoist*?

So far I've found `hoistGen` in https://github.com/ivanperez-keera/dunai/pull/84, and `hoist` here. I'm not sure there would be more.

Are those the only two that we'd have? If these can be called something that logically makes sense in terms of `morph` or `lift` (like `morphS` for `hoist`), then I think we finally eliminate the need for the new concept of hoisting and can move forward.

**Comment by turion** [comment]
`mmorph` is a well-known package amongst mathsier Haskellers, I think, say Kmettish people.

*For regular Haskellers, we would just adopt some naming scheme, and there the exact choice wouldn't matter. They don't need to understand `mmorph` etc. in order to understand dunai.
* But I'd strongly advise against picking a naming scheme that is incompatible packages like `mmorph`, because people who know it will be confused, or put off.

That's why I don't like:
```
morphS :: (forall c . m1 c -> m2 c) -> MSF m1 a b -> MSF m2 a b
```
If at all, it should be 
```
morphS :: MSF m1 a b -> MSF m2 a b
```
but of course there is no such top-level definition. Such a type signature might come up in a `where` clause or `let` binding.

Also, calling it anything like `lift` is very confusing, since `lift` is strongly associated to transformers. Generalising `lift` to `MSF`s should be:

```liftS :: MonadTrans t => MSF m a b -> MSF (t m) a b```

I still think the best name for applying a monad morphism to an `MSF` is `hoistS :: (forall c . m1 c -> m2 c) -> MSF m1 a b -> MSF m2 a b`. It says "hoist a monad morphism up to the level of `MSF`s". If you disagree, let's just rename everything except that thing, and open a separate issue?

**Comment by turion** [comment]
> So far I've found hoistGen in #84, and hoist here. I'm not sure there would be more.
> Are those the only two that we'd have?

Yes, those should be the only ones.

**Comment by ivanperez-keera** [comment]
> mmorph is a well-known package amongst mathsier Haskellers, I think, say Kmettish people.

I know Haskellers with a deep understanding of category theory who don't know what `mmorph` is at all. I do not have statistics about the community to stablish if this is general knowledge, or if our desired users would know it.

However, I very strongly disagree with the API stack he's been pushing for in Haskell. I think it makes Haskell harder to get into, it makes error messages extremely confusing, and it's not something I'd like to generally promote. I think it raises the bar to get into Haskell for non-mathematicians.

> *For regular Haskellers, we would just adopt some naming scheme, and there the exact choice wouldn't matter.

I disagree (which is why I've made such a fuzz about this). Vocabulary is hard to learn in general (which is, in part, why so many people find it so hard to learn new languages). Vocabulary is easier to learn when it relates to concepts we know (a house, a car). But when they are super-abstract and unknown, they become really hard. For anyone who doesn't know `mmorph`, the difference between lifting and hosting is going to be completely arbitrary, and the choice of when to call something a "lift" or a "hoist" is going to be impossible to make.

One of the beauties of vim, for example, is that the language is compositional. Learn a few concepts, combine them, and boom (!!!), you get a new thing. You don't need a custom command name for it.

> I still think the best name for applying a monad morphism to an MSF is hoistS 

I understand.

But since that choice does not satisfy us both, and neither does mine, can we find an alternative?

> If you disagree, let's just rename everything except that thing, and open a separate issue?

Let's see if we can find a reasonable middle ground and close this for long. If we have that dangling issue, it's going to be bugging me forever. This problem has been in my mind since September last year. I need to be able to sleep at night... :smile:

**Comment by turion** [comment]
** `hoist`

> I do not have statistics about the community to establish if this is general knowledge, or if our desired users would know it.

According to [this page](http://packdeps.haskellers.com/reverse), `mmorph` has 77 reverse dependencies on hackage. As a comparison, `MonadRandom` has 110, `megaparsec` 72, so that's very roughly how popular it is. `pipes` has 161, although probably many more 

> However, I very strongly disagree with the API stack he's been pushing for in Haskell. I think it makes Haskell harder to get into, it makes error messages extremely confusing, and it's not something I'd like to generally promote. I think it raises the bar to get into Haskell for non-mathematicians.

I think that has nothing to do with us. We don't depend on `mmorph`, nor does anyone have to understand `mmorph` in order to understand Dunai. It's really just about picking a word. We need a word that doesn't confuse/put off experienced haskellers and is understandable to inexperienced ones. That's why I thought that `hoistS` is a good choice, since "hoist" a synonym of "lift".

> the difference between lifting and hosting is going to be completely arbitrary, and the choice of when to call something a "lift" or a "hoist" is going to be impossible to make.

Ah, I think I'm finally beginning to understand your point. The problem is that they're too similar..?

But the concepts are very similar. `liftS :: MonadTrans t => MSF m a b -> MSF (t m) a b` is just (in my proposed nomenclature) `hoistS lift`. `liftS` is a special case of `hoistS`.

Or else I don't see what the problem really is. Dislike for the word `hoist`? I don't understand. It's a normal english word. It's in dictionaries. It's not going to confuse a lot of people.

> One of the beauties of vim, for example, is that the language is compositional. Learn a few concepts, combine them, and boom (!!!), you get a new thing. You don't need a custom command name for it.

Yes, that's great, and that's exactly what I want. The thing is, the function of type `(forall c . m1 c -> m2 c) -> MSF m1 a b -> MSF m2 a b` is not composed of anything else. It is a very fundamental thing.

** Alternatives

> can we find an alternative?
> transform, or morph, or change, or convert?

I would not recommend, because of risk of confusion:

* "transform": sounds like monad transformers
* "morph": sounds like monad morphism. `(forall c . m1 c -> m2 c) -> MSF m1 a b -> MSF m2 a b` _is not_ a monad morphism, or a generalisation thereof. It _takes_ as first argument a monad morphism.
* "change": Too general
* "convert": Hmm, sort of ok, I could live with it. But you would expect a function `convert` to convert data, rather than monads. But if we can't agree on anything else, let's stick with `convert`.

I have one more proposal, which I like better than `convert`: You know how there is `liftBase :: MonadBase b m => b a -> m a`. We could call our thing:

`liftAlong :: (forall c . m1 c -> m2 c) -> MSF m1 a b -> MSF m2 a b`

(Alternative: `liftAlongS`)

Example usage: `myOtherMSF = liftAlong myMonadMorphism myMSF`

You lift an `MSF` along a given monad morphism.

**Comment by ivanperez-keera** [comment]
I've temporarily made the decision of calling `hoistGen` `morphGS`. This is only so in a branch, so it's not released yet.

I know you don't like this. This may not be the end of the story, but we need to move forward. I'm not going to continue discussing this naming choice now, or soon.

It's hard to discuss each individual decision along a series of comments. I will add individual issues for the other points we need to discuss to make each of them simple enough.

Please do not open a separate issue for the `hoist` naming choice. I will do so in due time, and I will not forget, but I can't have it on my face all the time anymore.
