### ISSUE TITLE
Bearriver: reactimate thows undefined exception on correct input

### ISSUE THREAD

**Issue by miguel-negrao** [ivanperez-keera/dunai#266]
The code introduced at commit 2f21bff05a323a1f1f33558871e6ffcc73383220 doesn't seem correct.

If the first output of senseRest is a Nothing then there is an error:
```Haskell
import Data.IORef
import FRP.Yampa

main = do
  ref <- newIORef (0.0::Double)
  reactimate senseI (senseRest ref) (actuate ref) sf

senseI = do
  putStrLn "SenseI"
  return 45

senseRest ref _ = do
  v <- readIORef ref
  putStrLn "SenseRest"
  return (0.1, Nothing)

actuate ref _ x = do
  v <- readIORef ref
  putStrLn $ "actuate " ++ show x
  writeIORef ref (v+1)
  return (v >= 1)

sf = identity
```

```
SenseI
actuate 45
SenseRest
dunai-examples-bearriver-bouncingball: Prelude.undefined
CallStack (from HasCallStack):
  error, called at libraries/base/GHC/Err.hs:79:14 in base:GHC.Err
  undefined, called at src/FRP/BearRiver.hs:573:55 in bearriver-0.13.3-5dJQzIdyKtuHMkt9J9QooS:FRP.BearRiver
```

**Comment by turion** [comment]
Probably a regression test would be in order then

**Comment by miguel-negrao** [comment]
Regression test added in pull-request.

**Comment by ivanperez-keera** [comment]
I've been working on this commit for a bit.

The first thing I've done is to clean up and split the commit. I've adapted the code to follow dunai's coding rules (both in the cabal file and in the Haskell file). I've also separated the introduction of `dSwitch` and the improvements to `switch` into separate commits. Especially the latter seems not to belong with this issue (even if it's convenient or similar to something being done as part of it).

My changes are here: https://github.com/ivanperez-keera/dunai/tree/develop-fix-reactimate-add-dswitch

Now, I've just ran the following code, taken from this issue description, _on the current develop without the proposed fix_:
```haskell
{-# LANGUAGE PackageImports #-}
import Data.IORef
import "bearriver" FRP.Yampa

main = do
  ref <- newIORef (0.0::Double)
  reactimate senseI (senseRest ref) (actuate ref) sf

senseI = do
  putStrLn "SenseI"
  return 45

senseRest ref _ = do
  v <- readIORef ref
  putStrLn "SenseRest"
  return (0.1, Nothing)

actuate ref _ x = do
  v <- readIORef ref
  putStrLn $ "actuate " ++ show x
  writeIORef ref (v+1)
  return (v >= 1)

sf = identity
```
The only change I've made is to use `PackageImports` to identify `bearriver` as the package I want to use to import `FRP.Yampa`.

It doesn't crash for me:
```sh
$ ./Test && echo 1
SenseI
SenseRest
actuate 45
SenseRest
actuate 45
1
```

So I am confused about where the bug really is. I also wonder if the change to `senseFirst` is necessary (i.e., the fix won't work without that change) or just convenient (e.g., because it simplifies code). If the latter, then it should really be in a separate commit. Otherwise, it gives the impression that, to fix this issue, one would have to change `senseFirst`, which would not be the case (in that hypothetical scenario).

The status as of right now is that I can't replicate the issue.

**Comment by ivanperez-keera** [comment]
I've also rebased the branch https://github.com/ivanperez-keera/dunai/tree/develop-fix-reactimate-add-dswitch wrt. the current `develop` to diffs and merges.

**Comment by ivanperez-keera** [comment]
I have confirmed that this bug really exists, and the solution introduced by @miguel-negrao works well on my end.

I prefer to leave the regression test out. The reason is that, ideally, bearriver should pass Yampa's tests, and Yampa's QuickCheck tests should check for this case.
