### ISSUE TITLE
`dunai`: MonadRandom-0.6 is out of bounds

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#337]
See https://github.com/commercialhaskell/stackage/issues/6751. It seems `dunai` could easily update the `MonadRandom` version bound from 0.6 to 0.7. Quoting the maintainer:

> The major version bump is due to the fact that I finally removed some long-deprecated instances, for ErrorT and ListT. Most likely anything using MonadRandom will continue to work unchanged.

**Comment by ivanperez-keera** [comment]
I pushed a branch but it failed to compile. If a fix for MonadRandom is not published, we may be able to address it on our own by changing the constraint to something like:
```MonadRandom >= 0. 2 && ((base >= 4.8 && MonadRandom < 0.7) ||MonadRandom < 0.6)```

Let's give them a  couple of days or so. The next release of Dunai is scheduled for Dec 21st.

**Comment by ivanperez-keera** [comment]
I don't know how to specify `MonadRandom >= 0. 2 && ((base >= 4.8 && MonadRandom < 0.7) ||MonadRandom < 0.6)` in cabal.

Issue https://github.com/byorgey/MonadRandom/issues/51 has been closed as wontfix, although IMO it's a bug (simply because the package won't compile with versions of `base` withing the range of MonadRandom's `build-depends`. I've commented to see if it can be changed so that old versions of GHC won't pick it.

**Comment by turion** [comment]
> I don't know how to specify MonadRandom >= 0. 2 && ((base >= 4.8 && MonadRandom < 0.7) ||MonadRandom < 0.6) in cabal.

It's tricky to do that directly, but I think something like this should be possible (https://cabal.readthedocs.io/en/stable/cabal-package.html#conditions):

```
if impl(ghc>=8)
  MonadRandom >= 0.6 && < 0.7
else
  MonadRandom < 0.6
```

**Comment by ivanperez-keera** [comment]
You're right. I hadn't thought that `base` is "an exception" in a way :) Thanks!

**Comment by ivanperez-keera** [comment]
Funny. MonadRandom has just been revised, and now the extra complexity is not needed anymore. I'll create a separate issue to simplify the cabal file.
