### ISSUE TITLE
`dunai`: Implement `ListT` interface using `list-transformer`

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#418]
The current module exporting functions to work with the `ListT` monad relies on an implementation of `ListT` that is outdated and has been removed from newer versions of the `transformers` library.

Following the discussion in https://github.com/ivanperez-keera/dunai/discussions/368, it seems like we could replace it with the implementation in `list-transformer`.

**Comment by ivanperez-keera** [comment]
Pinging @madjestic @nullobject @turion @tomsmeding @DrewFenwick as participants in the original discussion. Please feel free to try the solution proposed in branch https://github.com/ivanperez-keera/dunai/tree/develop-list-transformer. The export and the dependency are controlled with a flag `list-transformer`.

**Comment by nullobject** [comment]
@ivanperez-keera I have tested the proposed branch in my project and it compiles no problem (I'm using Stack LTS 22.23).

This is great, because I previously couldn't even compile `dunai` with stack's newer version of `transformers` 🎉

Hopefully this means we can also get `dunai` included in stack's packages again.

If you cut a new release of dunai, will this change still be behind a flag?

**Comment by ivanperez-keera** [comment]
Thanks for trying it! Great to hear that it compiles.

Because this is an API-breaking change, my plan is to put it behind a flag for the next two versions and deprecate the older interface. On the third version released from now, the old interface will be removed and only the new one remain  (that'll be the release coming out on October 21, 2024).

The flag has `manual` set to False, so that it can be automatically set to `True` if needed to install with `transformers > 0.6`. Cabal has no problems dealing with that automatically.
