### ISSUE TITLE
What is the purpose of Data.VectorSpace.Specific?

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#46]
The module name of src/Data/VectorSpace/Specific.hs is weird. It does not really help. I would never intuitively go look for that there.

Do those instances belong somewhere else? Should the module be elsewhere?

**Comment by turion** [comment]
The issue is that instances from `Data.VectorSpace.Tuple` (supplying a `VectorSpace` for tuples of `VectorSpace`s do not go well with instances from `Data.VectorSpace.Fractional`. But often we want both an instance for `Double` and `(Double, Double)`. `Data.VectorSpace.Specific` contains instances for _specific_ types like `Float`, `Double` etc., and can be imported together with `Data.VectorSpace.Tuple`.

So it's really just a separation so that a library user can import as many instances at the same time as the Haskell type system would allow. If we were to choose some of the instances and put them all in `Data.VectorSpace`, we'd loose some if it.

But all this comes at the cost of orphan instances. So we could do the following: Change the `Fractional a => VectorSpace a` to a `newtype`-style instance. That way we might be able to put all instances into `Data.VectorSpace` and have no orphan instances, and noone needs to look for this strange module. Ok?

**Comment by ivanperez-keera** [comment]
And what happens if we put all of them in Data.VectorSpace?

**Comment by ivanperez-keera** [comment]
Could all of `https://github.com/ivanperez-keera/dunai/blob/develop/src/Data/VectorSpace/Specific.hs` be included into `https://github.com/ivanperez-keera/dunai/blob/develop/src/Data/VectorSpace.hs`.

**Comment by turion** [comment]
Then `Data.VectorSpace.Fractional` wouldn't compile I think because it would overlap with the instances from `Data.VectorSpace`. (But we could still `newtype` them.)

**Comment by ivanperez-keera** [comment]
I just tried to move everything in `Specific` into `VectorSpace` and the library does compile. What I don't know is if GHC will be confused when choosing instances for some types if some modules are imported.

**Comment by turion** [comment]
Ah maybe that's the problem then. If it ever occurs, let's just create a `newtype FractionalVectorSpace`.

**Comment by ivanperez-keera** [comment]
I just understood that everything inside `Data.VectorSpace.+` are instances.

**Comment by ivanperez-keera** [comment]
So, I think maybe better (intuitive) module names would be:

`Data.VectorSpace.Instances.Fractional`

and so on.

**Comment by turion** [comment]
Yes, agree. But that's an API change and would go in 0.3, right?

**Comment by ivanperez-keera** [comment]
There's been an API change that forces a version bump regardless. But this can wait until 0.4.
