### ISSUE TITLE
Functor, Applicative and Num instances could be more general

### ISSUE THREAD

**Issue by ivanperez-keera** [ivanperez-keera/dunai#56]
Not so much a suggestion. Merely observing that:

```
{-# LANGUAGE FlexibleInstances #-}
import Control.Applicative
import Control.Arrow

instance Arrow a => Functor (a b) where
  fmap f = (>>^ f)

instance Arrow a => Applicative (a b) where
  pure x  = arr (const x)
  f <*> x = (f &&& x) >>^ (uncurry ($))

instance (Arrow a, Num c) => Num (a b c) where
  (+)         = liftA2 (+)
  (-)         = liftA2 (-)
  (*)         = liftA2 (*)
  abs         = fmap abs
  signum      = fmap signum
  negate      = fmap negate
  fromInteger = pure . fromInteger
  
```

I'm not sure whether there's any gain or loss in terms of performance. I suspect similar things could be done for `VectorSpace`, and possibly almost any arrow that produces values that are instances of a class.

**Comment by turion** [comment]
That's right, and was probably known to Hughes when he proposed `Arrow`. (See also [this question](https://stackoverflow.com/questions/24668313/arrows-are-exactly-equivalent-to-applicative-functors).) I'm surprised not to find this in the standard library.

In terms of efficiency, I don't know, but the penalty can't be huge.

The only two things that speak against actually committing this code:

* Minor issue: We have defined `Functor m => Functor (MSF m a)` and we could actually define `Applicative m => Applicative (MSF m a)`, whereas `Arrow (MSF m)` always needs `Monad m`. But this generalisation is more of an academic issue, I guess, unless there are some `Applicative`s that are more efficient than some `Monad`s. (And then we'd still have to define `reactimate :: Applicative m => MSF m () () -> m ()`, which can be done.)
* Major issue: Committing these orphan instances could seriously confuse people, because they suddenly have `Functor`s and `Num`s lying around that they weren't aware of. (E.g. `Num (a -> Int)`) So if we want to add this code, it should be immediately specialised to `MSF m`, possibly naming all the implementations in general. E.g.:

```
{-# LANGUAGE FlexibleInstances #-}
import Control.Applicative
import Control.Arrow

fmapArr :: Arrow a => (c -> d) -> a b c -> a b d
fmapArr = (>>^ f)

instance Monad m => Functor (MSF m a b) where
  fmap f = fmapArr
```
Etc.

**Comment by ivanperez-keera** [comment]
Yeap. Nothing to do here, so closing this. Thanks, @turion .
