### ISSUE TITLE
Put examples under free licenses

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#8]
Consider putting all examples under GPL or similar.

**Comment by turion** [comment]
@ivanperez-keera, are you ok if I put all examples you wrote under the same license like dunai?

**Comment by ivanperez-keera** [comment]
I am. Dunai uses BSD3.

Note: Historically, the haskell community has used BSD-like licenses. I only use other licenses in very specific circumstances.

**Comment by ivanperez-keera** [comment]
For instance: haskanoid *must* have the license it has, because it combines resources from many different sources and with many licenses, and its combined status as a linked, binary thing is very unclear. While the distribution of those resources in raw form does not infringe anyone's copyright (credit is given where due and the respective authors' terms are respected), its distribution in binary form might.
