### ISSUE TITLE
Check out 'varying' and 'auto'

### ISSUE THREAD

**Issue by phischu** [ivanperez-keera/dunai#9]
You probably already know about them but since you explicitly invite "issues" like this, you could check out [`varying`](https://hackage.haskell.org/package/varying-0.6.0.0/docs/Control-Varying-Core.html) and [`auto`](https://hackage.haskell.org/package/auto-0.4.3.0/docs/Control-Auto.html). Perhaps you could add a comparison to the readme.

Or you could even try to merge your emphasis on the monad transformer aspect into [`varying` on github](https://github.com/schell/varying).

[`auto` is on github as well](https://github.com/mstksg/auto).

**Comment by turion** [comment]
Thank you very much for spotting these two. I personally wasn't aware of these packages. Is there a publication for either?

`varying` seems to do a subset of what we do. It's roughly the same age like our package, maybe younger. (It's always hard to tell when the actual development of a project started, and our development was private for quite some time.)

There are some weird ideas in `varying`, like `SplineT` and `VarT` being a monad transformer. I'm saying weird because streams aren't a good monad. We carefully avoid that (it's maybe better to think about them as applicative transformers (yes, these exist and can be nontrivial)). Also, `SplineT` is just `VarT` with an added `EitherT`/`ExceptT`-layer in the monad stack, so I don't see why it's necessary to have a separate type.

`auto` is a bit like a fused monadic stream function. That's interesting, we were planning on adding something like this to our framework. It's definitely older. I can't see anything towards monad transformers.

Maybe we can add compatibility layers if people want to switch from one to the other.

Are there any publications associated to varying or auto? (I didn't find any, but maybe I overlooked something obvious)

**Comment by phischu** [comment]
There are no publications i know of.

> There are some weird ideas in varying, like SplineT and VarT being a monad transformer.

Oh, I missed that `MSF` does not have a monad instance. Why aren't streams a good monad? For example the [`streaming package`](https://hackage.haskell.org/package/streaming) has a monad instance for its streams.

The distinguishing feature in `auto` is that you can serialize `Auto`s if I understand correctly.

Thanks for your friendly reply.

**Comment by rainbyte** [comment]
I think that having a comparison in the readme would be really useful.
Other libraries like [netwire](https://github.com/esoeylemez/netwire) or [reactive-banana](https://hackage.haskell.org/package/reactive-banana) could be included.

Maybe this should be reported as a new issue...?

**Comment by turion** [comment]
One mid-term goal would be be an "inverse reactive zoo" that explains most common frameworks in terms of monadic stream functions, but we're not there yet. Thanks for the input.

**Comment by ivanperez-keera** [comment]
Just like bearriver is for Yampa, the reverse zoo could be a collection of libraries that can, in principle, be used instead of the original library to link programs, together with examples that work in both the original implementation and our MSF-based re-implementations.

reactive-banana is push-based, so my guess is that it will be harder to get right, if we can at all.

netwire, on the other hand, could be possible. I don't have a lot of time these days, but I'm tempted to try.

**Comment by ivanperez-keera** [comment]
After conversations with Daniel Winograd-Cort: MSFs implement wormholes (it's exactly how he did it).

**Comment by ivanperez-keera** [comment]
Varying now links to the article [Functional Reactive Programming, refactored](https://dl.acm.org/citation.cfm?id=2976010).

**Comment by ivanperez-keera** [comment]
Like you have said, the general case of auto is:
```
data Auto m a b = ...
                | AutoArbM    (Get (Auto m a b)) Put !(a -> m (b, Auto m a b))
```

Which I think is similar to our case, except that it gives an `Auto` in an exception/state monad (`Get`), and a `Writer` (`Put`).

What I wonder is why it's necessary to have so many cases for value constructors for `Auto`, and why the serialization mechanism needs to be with the value constructors.

**Comment by ivanperez-keera** [comment]
Given the very many implementations of RP/FRP things in Haskell, this looks like a ticket that will never ever be completed or closed. There will always be more.

It probably would make things move forward more quickly to have one ticket to inaugurate the Reverse Zoo, and another one for each of the implementations that we really want to compare (with care: there's so many that, if we just start adding one issue for each of the existing implementations, we'll have dozens of issues that nobody will ever work on but we'll never be able to close).

**Comment by turion** [comment]
Yes, starting the reverse FRP zoo closes this issue, and each package that we should implement is a new issue on the reverse FRP zoo (probably a repository with several separate packages).

**Comment by ivanperez-keera** [comment]
See: https://github.com/ivanperez-keera/dunai/issues/52.

Do you think this should be a separate repo, or just something in examples?

**Comment by turion** [comment]
For my taste, it can live in the same repo. (Just not in the same cabal package.)

**Comment by ivanperez-keera** [comment]
As per @turion's comment and #52, I'm closing this ticket :)
